config/routes.rb
Rails.application.routes.draw do
	# Public pages
	root "pages#home"
	get 'pricing', to: 'pages#pricing'

	# Webhooks
	post 'coupons/webhook_stripe', to: 'coupons#webhook_stripe'

	#App
	devise_for :users
	get 'dashboard', to: 'dashboards#dashboard'
	resources :users do 
		resources :custom_prices
	end
	resources :countries, only: [:index]
	resources :quotes, only: [:index]

	#API
	namespace 'api', defaults: { format: :json } do
		namespace :v1 do
			post 'authenticate', to: 'authentication#authenticate'
			post 'quote', to: 'quotes#create'
		end
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<%= favicon_link_tag image_path('earth-2.svg'), :rel => 'icon', :type =>  'image/png' %>
		<title><%= meta_title %></title>
		<meta name="description" content="<%= meta_description %>">
	
		<!-- Facebook Open Graph data -->
		<meta property="og:title" content="<%= meta_title %>" />
		<meta property="og:type" content="website" />
		<meta property="og:url" content="<%= request.original_url %>" />
		<meta property="og:image" content="<%= meta_image %>" />
		<meta property="og:description" content="<%= meta_description %>" />
		<meta property="og:site_name" content="<%= meta_title %>" />
	
		<!-- Twitter Card data -->
		<meta name="twitter:card" content="summary_large_image">
		<meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
		<meta name="twitter:title" content="<%= meta_title %>">
		<meta name="twitter:description" content="<%= meta_description %>">
		<meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
		<meta name="twitter:image:src" content="<%= meta_image %>">
	
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>

		<%= yield :extra_styles %>

		<%= stylesheet_link_tag 'app', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= stylesheet_link_tag 'icons', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

	</head>

	<body>
		<div class="wrapper">
			<%= render 'layouts/partials/left-sidebar'%>
			<div class="content-page">
			<div class="content">
				<%= render 'layouts/partials/topbar'%>
				<%= yield %>
			</div>
			<%= render 'layouts/partials/footer'%>
			</div>
		</div>	

		<%= javascript_include_tag 	'application', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 	'vendor', 'data-turbolinks-track': 'reload' %>

		<%= yield :extra_script %>

	</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
	<head>
		<%= favicon_link_tag image_path('earth-2.svg'), :rel => 'icon', :type =>  'image/png' %>
		<title><%= meta_title %></title>
		<meta name="description" content="<%= meta_description %>">
	
		<!-- Facebook Open Graph data -->
		<meta property="og:title" content="<%= meta_title %>" />
		<meta property="og:type" content="website" />
		<meta property="og:url" content="<%= request.original_url %>" />
		<meta property="og:image" content="<%= meta_image %>" />
		<meta property="og:description" content="<%= meta_description %>" />
		<meta property="og:site_name" content="<%= meta_title %>" />
	
		<!-- Twitter Card data -->
		<meta name="twitter:card" content="summary_large_image">
		<meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
		<meta name="twitter:title" content="<%= meta_title %>">
		<meta name="twitter:description" content="<%= meta_description %>">
		<meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
		<meta name="twitter:image:src" content="<%= meta_image %>">
	
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>
		<%= stylesheet_link_tag    'icons', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= stylesheet_link_tag    'app', media: 'all', 'data-turbolinks-track': 'reload' %>
	</head>

	<body class="authentication-bg pb-0" data-layout-config='{"darkMode":false}'>
		<div class="auth-fluid">
			<!--Auth fluid left content -->
			<div class="auth-fluid-form-box">
				<div class="align-items-center d-flex h-100">
					<div class="card-body">
	
						<!-- Logo -->
						<div class="auth-brand text-center text-lg-left">
							<a href="<%= root_path %>" class="logo-dark">
								<span><img src="<%= image_path('saasinit-lg.png') %>" alt="" height="40px"></span>
							</a>
						</div>
	
						<%= yield %>
						<%= render "devise/shared/links" %>
	
					</div> <!-- end .card-body -->
				</div> <!-- end .align-items-center.d-flex.h-100-->
			</div>
			<!-- end auth-fluid-form-box-->
	
			<!-- Auth fluid right content -->
			<div class="auth-fluid-right text-center">
				<div class="auth-user-testimonial">
					<h2 class="mb-3">I love the color!</h2>
					<p class="lead"><i class="mdi mdi-format-quote-open"></i> It's a elegent templete. I love it very much! . <i class="mdi mdi-format-quote-close"></i>
					</p>
					<p>
						- Hyper Admin User
					</p>
				</div> <!-- end auth-user-testimonial-->
			</div>
			<!-- end Auth fluid right content -->
		</div>
		<!-- end auth-fluid-->
		<footer>
			<%= javascript_include_tag 'vendor', 'data-turbolinks-track': 'reload' %>
			<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
			<%= yield :extra_script %>
		</footer>
	</body>
</html>

app/views/layouts/partials/_footer.html.erb
<!-- Footer Start -->
<footer class="footer">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-6">
				<script>document.write(new Date().getFullYear())</script> © Hyper - Coderthemes.com
			</div>
			<div class="col-md-6">
				<div class="text-md-right footer-links d-none d-md-block">
					<a href="javascript: void(0);">About</a>
					<a href="javascript: void(0);">Support</a>
					<a href="javascript: void(0);">Contact Us</a>
				</div>
			</div>
		</div>
	</div>
</footer>
<!-- end Footer -->

app/views/layouts/partials/_left-sidebar.html.erb
<!-- ========== Left Sidebar Start ========== -->
<div class="left-side-menu">

	<!-- LOGO -->
	<%= link_to root_path, class: "logo text-center logo-light" do %>
		<span class="logo-lg">
			<img src="<%= image_url('exportator-logo.png') %>" alt="" height="50">
		</span>
		<span class="logo-sm">
			<img src="<%= image_url('earth-3.svg') %>" alt="" height="50">
		</span>
	<% end %>

	<!-- LOGO -->
	<%= link_to root_path, class: "logo text-center logo-dark" do %>
		<span class="logo-lg">
			<img src="<%= image_url('exportator-logo.png') %>" alt="" height="50">
		</span>
		<span class="logo-sm">
			<img src="<%= image_url('earth-3.svg') %>" alt="" height="50">
		</span>
	<% end %>
	
	<div class="h-100" id="left-side-menu-container" data-simplebar>

		<!--- Sidemenu -->
		<ul class="metismenu side-nav">

			<li class="side-nav-title side-nav-item">Navigation</li>

			<li class="side-nav-item">
				<%= link_to dashboard_path, class: "side-nav-link" do %>
					<i class="uil-home-alt"></i>
					<span> Dashboard </span>
				<% end %>
			</li>

			<li class="side-nav-title side-nav-item">Export</li>

			<li class="side-nav-item">
				<%= link_to user_custom_prices_path(current_user), class: "side-nav-link" do %>
					<i class="uil-ticket"></i>
					<span> Coupons </span>
				<% end %>
			</li>

			<li class="side-nav-item">
				<%= link_to quotes_path, class: "side-nav-link" do %>
					<i class="uil-cog"></i>
					<span> Logs </span>
				<% end %>
			</li>

			<li class="side-nav-title side-nav-item">Public</li>

			<li class="side-nav-item">
				<%= link_to user_path(current_user), class: "side-nav-link" do %>
					<i class="uil-shop"></i>
					<span> Your page </span>
				<% end %>
			</li>

			<li class="side-nav-title side-nav-item mt-1">Settings</li>

			<li class="side-nav-item">
				<%= link_to edit_user_path(current_user), class: "side-nav-link" do %>
					<i class="uil-user"></i>
					<span> User </span>
				<% end %>
			</li>

			<li class="side-nav-item">
				<%= link_to user_path(current_user), class: "side-nav-link" do %>
					<i class="uil-dollar-alt"></i>
					<span> Stripe </span>
				<% end %>
			</li>
			
		</ul>

		<%= render "shared/help_box", 	image_path: "earth-2.svg",
										title: "Find new customers!",
										subtitle: "Make your company page public and get in the newsletter!",
										cta: "Create",
										cta_url: dashboard_path %>
		<!-- End Sidebar -->

		<div class="clearfix"></div>

	</div>
	<!-- Sidebar -left -->

</div>
<!-- Left Sidebar End -->

app/views/layouts/partials/_public_topbar.html.erb
<nav class="navbar navbar-expand-lg py-lg-3 navbar-dark">
	<div class="container">
	
		<!-- logo -->
		<a href="index.html" class="navbar-brand mr-lg-5">
			<img src="assets/images/logo.png" alt="" class="logo-dark" height="18">
		</a>
	
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
			<i class="mdi mdi-menu"></i>
		</button>
	
		<!-- menus -->
		<div class="collapse navbar-collapse" id="navbarNavDropdown">
	
			<!-- left menu -->
			<ul class="navbar-nav mr-auto align-items-center">
				<li class="nav-item mx-lg-1">
					<a class="nav-link active" href="">Home</a>
				</li>
				<li class="nav-item mx-lg-1">
					<a class="nav-link" href="">Features</a>
				</li>
				<li class="nav-item mx-lg-1">
					<a class="nav-link" href="<%= pricing_path %>">Pricing</a>
				</li>
				<li class="nav-item mx-lg-1">
					<a class="nav-link" href="">FAQs</a>
				</li>
				<li class="nav-item mx-lg-1">
					<a class="nav-link" href="">Clients</a>
				</li>
				<li class="nav-item mx-lg-1">
					<a class="nav-link" href="">Contact</a>
				</li>
			</ul>
	
			<!-- right menu -->
			<ul class="navbar-nav ml-auto align-items-center">
				<li class="nav-item mr-0">
					<a href="https://themes.getbootstrap.com/product/hyper-responsive-admin-dashboard-template/" target="_blank" class="nav-link d-lg-none">Purchase now</a>
					<a href="https://themes.getbootstrap.com/product/hyper-responsive-admin-dashboard-template/" target="_blank" class="btn btn-sm btn-light btn-rounded d-none d-lg-inline-flex">
						<i class="mdi mdi-basket mr-2"></i> Purchase Now
					</a>
				</li>
			</ul>
	
		</div>
	</div>
</nav>

app/views/layouts/partials/_topbar.html.erb
<!-- Topbar Start -->
<div class="navbar-custom">
		<ul class="list-unstyled topbar-right-menu float-right mb-0">
			<li class="dropdown notification-list d-lg-none">
				<a class="nav-link dropdown-toggle arrow-none" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
					<i class="dripicons-search noti-icon"></i>
				</a>
				<div class="dropdown-menu dropdown-menu-animated dropdown-lg p-0">
					<form class="p-3">
						<input type="text" class="form-control" placeholder="Search ..." aria-label="Recipient's username">
					</form>
				</div>
			</li>
			<li class="dropdown notification-list topbar-dropdown">
				<a class="nav-link dropdown-toggle arrow-none" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
					<img src="<%= image_url('exportator-logo.png') %>" alt="user-image" class="mr-0 mr-sm-1" height="12"> 
					<span class="align-middle d-none d-sm-inline-block">English</span> <i class="mdi mdi-chevron-down d-none d-sm-inline-block align-middle"></i>
				</a>
				<div class="dropdown-menu dropdown-menu-right dropdown-menu-animated topbar-dropdown-menu">
	
					<!-- item-->
					<a href="javascript:void(0);" class="dropdown-item notify-item">
						<img src="<%= image_url('exportator-logo.png') %>" alt="user-image" class="mr-1" height="12"> <span class="align-middle">German</span>
					</a>
	
					<!-- item-->
					<a href="javascript:void(0);" class="dropdown-item notify-item">
						<img src="<%= image_url('exportator-logo.png') %>" alt="user-image" class="mr-1" height="12"> <span class="align-middle">Italian</span>
					</a>
					
					<!-- item-->
					<a href="javascript:void(0);" class="dropdown-item notify-item">
						<img src="<%= image_url('exportator-logo.png') %>" alt="user-image" class="mr-1" height="12"> <span class="align-middle">Spanish</span>
					</a>
	
					<!-- item-->
					<a href="javascript:void(0);" class="dropdown-item notify-item">
						<img src="<%= image_url('exportator-logo.png') %>" alt="user-image" class="mr-1" height="12"> <span class="align-middle">Russian</span>
					</a>
	
				</div>
			</li>
	
			<li class="dropdown notification-list">
				<a class="nav-link dropdown-toggle arrow-none" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
					<i class="dripicons-bell noti-icon"></i>
					<span class="noti-icon-badge"></span>
				</a>
				<div class="dropdown-menu dropdown-menu-right dropdown-menu-animated dropdown-lg">
	
					<!-- item-->
					<div class="dropdown-item noti-title">
						<h5 class="m-0">
							<span class="float-right">
								<a href="javascript: void(0);" class="text-dark">
									<small>Clear All</small>
								</a>
							</span>Notification
						</h5>
					</div>
	
					<div style="max-height: 230px;" data-simplebar>
						<!-- item-->
						<a href="javascript:void(0);" class="dropdown-item notify-item">
							<div class="notify-icon bg-primary">
								<i class="mdi mdi-comment-account-outline"></i>
							</div>
							<p class="notify-details">Caleb Flakelar commented on Admin
								<small class="text-muted">1 min ago</small>
							</p>
						</a>
	
						<!-- item-->
						<a href="javascript:void(0);" class="dropdown-item notify-item">
							<div class="notify-icon bg-info">
								<i class="mdi mdi-account-plus"></i>
							</div>
							<p class="notify-details">New user registered.
								<small class="text-muted">5 hours ago</small>
							</p>
						</a>
	
						<!-- item-->
						<a href="javascript:void(0);" class="dropdown-item notify-item">
							<div class="notify-icon">
								<img src="<%= image_url('exportator-logo.png') %>" class="img-fluid rounded-circle" alt="" /> </div>
							<p class="notify-details">Cristina Pride</p>
							<p class="text-muted mb-0 user-msg">
								<small>Hi, How are you? What about our next meeting</small>
							</p>
						</a>
	
						<!-- item-->
						<a href="javascript:void(0);" class="dropdown-item notify-item">
							<div class="notify-icon bg-primary">
								<i class="mdi mdi-comment-account-outline"></i>
							</div>
							<p class="notify-details">Caleb Flakelar commented on Admin
								<small class="text-muted">4 days ago</small>
							</p>
						</a>
	
						<!-- item-->
						<a href="javascript:void(0);" class="dropdown-item notify-item">
							<div class="notify-icon">
								<img src="<%= image_url('exportator-logo.png') %>" class="img-fluid rounded-circle" alt="" /> </div>
							<p class="notify-details">Karen Robinson</p>
							<p class="text-muted mb-0 user-msg">
								<small>Wow ! this admin looks good and awesome design</small>
							</p>
						</a>
	
						<!-- item-->
						<a href="javascript:void(0);" class="dropdown-item notify-item">
							<div class="notify-icon bg-info">
								<i class="mdi mdi-heart"></i>
							</div>
							<p class="notify-details">Carlos Crouch liked
								<b>Admin</b>
								<small class="text-muted">13 days ago</small>
							</p>
						</a>
					</div>
	
					<!-- All-->
					<a href="javascript:void(0);" class="dropdown-item text-center text-primary notify-item notify-all">
						View All
					</a>
	
				</div>
			</li>
	
			<li class="dropdown notification-list d-none d-sm-inline-block">
				<a class="nav-link dropdown-toggle arrow-none" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
					<i class="dripicons-view-apps noti-icon"></i>
				</a>
				<div class="dropdown-menu dropdown-menu-right dropdown-menu-animated dropdown-lg p-0">
	
					<div class="p-2">
						<div class="row no-gutters">
							<div class="col">
								<a class="dropdown-icon-item" href="#">
									<img src="<%= image_url('exportator-logo.png') %>" alt="slack">
									<span>Slack</span>
								</a>
							</div>
							<div class="col">
								<a class="dropdown-icon-item" href="#">
									<img src="<%= image_url('exportator-logo.png') %>" alt="Github">
									<span>GitHub</span>
								</a>
							</div>
							<div class="col">
								<a class="dropdown-icon-item" href="#">
									<img src="<%= image_url('exportator-logo.png') %>" alt="dribbble">
									<span>Dribbble</span>
								</a>
							</div>
						</div>
	
						<div class="row no-gutters">
							<div class="col">
								<a class="dropdown-icon-item" href="#">
									<img src="<%= image_url('exportator-logo.png') %>" alt="bitbucket">
									<span>Bitbucket</span>
								</a>
							</div>
							<div class="col">
								<a class="dropdown-icon-item" href="#">
									<img src="<%= image_url('exportator-logo.png') %>" alt="dropbox">
									<span>Dropbox</span>
								</a>
							</div>
							<div class="col">
								<a class="dropdown-icon-item" href="#">
									<img src="<%= image_url('exportator-logo.png') %>" alt="G Suite">
									<span>G Suite</span>
								</a>
							</div>
				
						</div>
					</div>
	
				</div>
			</li>
	
			<li class="notification-list">
				<a class="nav-link right-bar-toggle" href="javascript: void(0);">
					<i class="dripicons-gear noti-icon"></i>
				</a>
			</li>
	
			<li class="dropdown notification-list">
				<a class="nav-link dropdown-toggle nav-user arrow-none mr-0" data-toggle="dropdown" href="#" role="button" aria-haspopup="false"
					aria-expanded="false">
					<span class="account-user-avatar"> 
						<img src="<%= image_url('exportator-logo.png') %>" alt="user-image" class="rounded-circle">
					</span>
					<span>
						<span class="account-user-name">Dominic Keller</span>
						<span class="account-position">Founder</span>
					</span>
				</a>
				<div class="dropdown-menu dropdown-menu-right dropdown-menu-animated topbar-dropdown-menu profile-dropdown">
					<!-- item-->
					<div class=" dropdown-header noti-title">
						<h6 class="text-overflow m-0">Welcome !</h6>
					</div>
	
					<!-- item-->
					<a href="javascript:void(0);" class="dropdown-item notify-item">
						<i class="mdi mdi-account-circle mr-1"></i>
						<span>My Account</span>
					</a>
	
					<!-- item-->
					<a href="javascript:void(0);" class="dropdown-item notify-item">
						<i class="mdi mdi-account-edit mr-1"></i>
						<span>Settings</span>
					</a>
	
					<!-- item-->
					<a href="javascript:void(0);" class="dropdown-item notify-item">
						<i class="mdi mdi-lifebuoy mr-1"></i>
						<span>Support</span>
					</a>
	
					<!-- item-->
					<a href="javascript:void(0);" class="dropdown-item notify-item">
						<i class="mdi mdi-lock-outline mr-1"></i>
						<span>Lock Screen</span>
					</a>
	
					<!-- item-->
					<a href="javascript:void(0);" class="dropdown-item notify-item">
						<i class="mdi mdi-logout mr-1"></i>
						<span>Logout</span>
					</a>
	
				</div>
			</li>
	
		</ul>
		<button class="button-menu-mobile open-left disable-btn">
			<i class="mdi mdi-menu"></i>
		</button>
		<div class="app-search dropdown d-none d-lg-block">
			<form>
				<div class="input-group">
					<input type="text" class="form-control dropdown-toggle" placeholder="Search..." id="top-search">
					<span class="mdi mdi-magnify search-icon"></span>
					<div class="input-group-append">
						<button class="btn btn-primary" type="submit">Search</button>
					</div>
				</div>
				 
			</form>
	
			<div class="dropdown-menu dropdown-menu-animated dropdown-lg" id="search-dropdown">
				<!-- item-->
				<div class="dropdown-header noti-title">
					<h5 class="text-overflow mb-2">Found <span class="text-danger">17</span> results</h5>
				</div>
	
				<!-- item-->
				<a href="javascript:void(0);" class="dropdown-item notify-item">
					<i class="uil-notes font-16 mr-1"></i>
					<span>Analytics Report</span>
				</a>
	
				<!-- item-->
				<a href="javascript:void(0);" class="dropdown-item notify-item">
					<i class="uil-life-ring font-16 mr-1"></i>
					<span>How can I help you?</span>
				</a>
	
				<!-- item-->
				<a href="javascript:void(0);" class="dropdown-item notify-item">
					<i class="uil-cog font-16 mr-1"></i>
					<span>User profile settings</span>
				</a>
	
				<!-- item-->
				<div class="dropdown-header noti-title">
					<h6 class="text-overflow mb-2 text-uppercase">Users</h6>
				</div>
	
				<div class="notification-list">
					<!-- item-->
					<a href="javascript:void(0);" class="dropdown-item notify-item">
						<div class="media">
							<img class="d-flex mr-2 rounded-circle" src="<%= image_url('exportator-logo.png') %>" alt="Generic placeholder image" height="32">
							<div class="media-body">
								<h5 class="m-0 font-14">Erwin Brown</h5>
								<span class="font-12 mb-0">UI Designer</span>
							</div>
						</div>
					</a>
	
					<!-- item-->
					<a href="javascript:void(0);" class="dropdown-item notify-item">
						<div class="media">
							<img class="d-flex mr-2 rounded-circle" src="<%= image_url('exportator-logo.png') %>" alt="Generic placeholder image" height="32">
							<div class="media-body">
								<h5 class="m-0 font-14">Jacob Deo</h5>
								<span class="font-12 mb-0">Developer</span>
							</div>
						</div>
					</a>
				</div>
			</div>
		</div>
	</div>
	<!-- end Topbar -->